server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true

auth:
  jwt:
    private-key-path: classpath:keys/private_key.pem
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 30

security:
  jwt:
    public-key-path: classpath:keys/public_key.pem
    issuer: auth-service

app:
  cleanup:
    refresh-token-cron: "0 0 * * * *"
