package fedod.meal.service.dto;

import fedod.meal.service.entity.enums.MealType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.util.List;

public record CreateDishRequest(
        // For curated dishes (food.ru import) id is supplied explicitly.
        // For AI-generated dishes id may be null — the service will allocate a unique negative id.
        Long id,
        String url,
        @NotBlank @Size(max = 255) String title,
        String description,
        String dishImage,
        BigDecimal calories,
        BigDecimal protein,
        BigDecimal fat,
        BigDecimal carbs,
        String readyIn,
        String kitchenTime,
        String cuisine,
        String categoryPath,
        String recipe,
        @NotNull MealType mealType,
        List<String> allergens,
        List<String> ingredients,

        // Set to true by external/AI services when the dish was generated by an LLM.
        // If null, defaults to false.
        Boolean aiGenerated,

        // True when the dish has been manually reviewed and approved by an administrator.
        // External services (LLM-based) MUST NOT set this to true — verification is internal.
        // If null, defaults to false.
        Boolean verified
) {
}
