server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/**

            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/users/**

            - id: meal-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/dishes/**

            - id: meal-plan-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/meal-plans/**

            - id: meal-plan-orchestrator
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/orchestrator/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
