server:
  port: 8085

spring:
  application:
    name: meal-plan-orchestrator
  datasource:
    url: jdbc:postgresql://localhost:5432/orchestrator_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      group-id: meal-plan-orchestrator
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

security:
  jwt:
    public-key-path: classpath:keys/public_key.pem
    issuer: auth-service
    enabled: true

kafka:
  topics:
    generate-mealplan-command: generate.mealplan.command
    replace-mealplan-command: replace.mealplan.command
    job-updated-event: job.updated.event

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
